### ISSUE TITLE
Almost always a first result of one of the test-packages will return NaN

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/perf-tester#7]
hey,

if I run the performance tester I do get a lot of NaN on the first run. It looks like this
![nanresult](https://user-images.githubusercontent.com/24378/35765858-2ffba204-08cd-11e8-9647-7899a6d5d2a6.PNG)

Apparently, _scoreMessage get's somehow called before we call it ourself? it has no data then... so if I add this little safety check in `perf-tester.js` the problem just disappears.
```js
    _scoreMessage(e) {
      if (this.afterScore) {
        // START of edit
        if (!e.data) {
          return;
        }
        // END of edit
        let info = e.data;
        if (typeof info !== 'object') {
          info = {time: info};
        }
        info.time = parseInt(info.time);
        this.afterScore(info);
      }
    }
```

would you like a PR?

PS: the same problem appears in the node version (if this is a valid solution I can take a look there as well)

**Comment by TimvdLippe** [comment]
Yes feel free to submit a PR :)

**Comment by bashmish** [comment]
The fix doesn't work for me. Another MR https://github.com/PolymerLabs/perf-tester/pull/9/files

![image](https://user-images.githubusercontent.com/137844/35847556-0fc1c04a-0b1b-11e8-8a1f-9d539891c1a0.png)
